# Generated by Django 5.2.5 on 2025-11-27 12:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_platformsettings_app_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRewardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='O código que os usuários devem digitar para resgatar o subsídio.', max_length=20, unique=True, verbose_name='Código de Resgate')),
                ('reward_amount', models.DecimalField(decimal_places=2, help_text='O valor em Kwanzas que o usuário ganhará ao resgatar o código.', max_digits=10, verbose_name='Valor do Subsídio (Kz)')),
                ('is_active', models.BooleanField(default=True, help_text='Apenas um código deve estar ativo por vez.', verbose_name='Ativo')),
                ('created_date', models.DateField(default=datetime.date.today, help_text='Este código é válido para resgate nesta data (UTC). Idealmente, alterado diariamente.', verbose_name='Data de Criação/Validade')),
            ],
            options={
                'verbose_name': 'Código de Subsídio Diário',
                'verbose_name_plural': 'Códigos de Subsídio Diários',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_date',), name='unique_active_code_per_day')],
            },
        ),
        migrations.CreateModel(
            name='UserRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(default=datetime.date.today, verbose_name='Data do Resgate')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='Horário do Resgate')),
                ('reward_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailyrewardcode', verbose_name='Código Resgatado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate de Subsídio',
                'verbose_name_plural': 'Resgates de Subsídios',
                'unique_together': {('user', 'claim_date')},
            },
        ),
    ]
