# Generated by Django 5.2.5 on 2025-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailyrewardcode_userrewardclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_level_invested_paid_to_inviter',
            field=models.BooleanField(default=False, verbose_name='Subsídio do Primeiro Nível Pago'),
        ),
    ]
