# Generated by Django 5.2.5 on 2025-12-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_first_level_invested_paid_to_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='telegram_link',
            field=models.URLField(default='#', help_text='O link para o canal/grupo do Telegram que aparecerá no botão de apoio.', verbose_name='Link do canal/grupo do Telegram'),
            preserve_default=False,
        ),
    ]
