# Generated by Django 5.2.5 on 2025-12-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_platformsettings_telegram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='telegram_link',
        ),
    ]
