# Generated by Django 5.2.5 on 2025-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_platformsettings_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='telegram_link',
            field=models.URLField(default='#', help_text='O link para o canal ou grupo do Telegram que aparecerá no botão de apoio.', verbose_name='Link do Canal/Grupo do Telegram'),
        ),
    ]
